config/routes.rb
Cranker::Application.routes.draw do
  devise_for :users
  
  root :to => "home#index"
  match 'equipments' => 'home#equipments', :as => :equipments
  match 'about'    => 'home#about',    :as => :about
  match 'contacts' => 'home#contacts', :as => :contacts
  post 'inquery' => 'home#inquery', :as => :inquery
  match 'load' => 'home#load', :as => :load
  resources :products

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
end

app/models/model.rb
class Model < ActiveRecord::Base
  has_many :products
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image, :styles => { :thumb => "150x150>" }
  
  validates_presence_of :name
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pictures
  belongs_to :brand
  belongs_to :model
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  layout :resolve_layout
  
  respond_to :html, :j
  
  def index
  end
  
  def about
  end
  
  def equipments
  end
  
  def contacts
  end
  
  def load
    @body = HTTParty.get(params['url']).body.html_safe
  end
  
  def inquery
    if params[:subject].blank? || params[:body].blank? || params[:name].blank? || params[:email].blank? || params[:company].blank?
      flash[:error] = "Please fill in both Name, Email, Company name, Subject and Content. Thanks!"
      redirect_to contacts_url
    else 
      CustomerMailer.inquery(params).deliver 
      flash[:notice] = "Your inquery has been successfully submitted!"
      redirect_to root_url 
    end
  end
  
  private

  def resolve_layout
    case action_name
    when "equipments", "contacts"
      "product"
    when "load"
      nil
    else
      "application"
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'product'
  
  inherit_resources
  expose(:products) { @products }
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
  def nice_link(link_class, name, path, opts={})
    link_class += (current_page?(path) ? ' current' : '')
    content_tag :li, :class => link_class do
      link_to name, path, opts
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def prod_box(prod, &block)
    div_for prod, :class => prod_class(prod), &block
  end
  
  def prod_class(prod)
    [:brand, :model].map {|f| f.to_s + '_' + prod.send("#{f}_id").to_s }.join(' ')
  end
end

app/views/home/_google.html.erb
<script type="text/javascript">
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24529558-1']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
 
</script>

app/views/home/about.html.erb
<%= content_for :slides do %>
  <div><%= image_tag('products/CumminsM11.png')%></div>
  <div><%= image_tag('products/CUMMINSNT855.png')%></div>
  <div><%= image_tag('products/k38.png')%></div>
  <div><%= image_tag('products/k50.png')%></div>
<% end %>

<%= content_for :meta_info do %>
  <meta name="description" content=" Liaoning 518 Internal Combustion Engine Fittings Company provides high quality crankshafts for diesel engines, Cummins Crankshafts, Caterpillar crankshafts, Perkins Crankshafts, DEUTZ crankshafts, Steyr Crankshafts, ISUZU Crankshafts and much more.">
  <meta name="keywords" content=" tractor, part, parts, engine, engine parts, diesel engine, diesel engine parts, diesel generator crankshaft, engine crankshaft, diesel engine crankshaft, crankshaft, marine crankshaft, marine diesel, Marine engine parts, crank, cranks, China marine diesel engine crankshaft manufacturer, China marine crankshaft manufacturer, forged steel crankshaft, Rebuilt diesel engines, cummins crankshaft,  cummins crank, caterpillar crankshaft, cummins engine parts">
<% end %>

<%= content_for :title do %>
  About Us
<% end %>

<%= content_for :header do %>
  About Us
<% end %>

<%= content_for :js do %>
  <script> App.loadContent('#about_div', "http://www.heyook.com/dieselcrankshafts.com/about.html"); </script>
<% end %>

<div id="about_div" class="overview">

</div>

app/views/home/contacts.html.erb
<%= content_for :slides do %>
  <div><%= image_tag('contact_us.png')%></div>
<% end %>

<%= content_for :title do %>
  Contacts
<% end %>

<%= content_for :meta_info do %>
  <meta name="description" content=" Liaoning 518 Internal Combustion Engine Fittings Company provides high quality crankshafts for diesel engines, Cummins Crankshafts, Cummins K50, Cummins K38, Cummins K19, Caterpillar crankshafts, Perkins Crankshafts, DEUTZ crankshafts, Steyr Crankshafts, ISUZU Crankshafts and much more.">
  <meta name="keywords" content=" Cummins K50 crankshaft, Cummins K38 crankshaft, Cummins K19 crankshaft, Cummins NT855 crankshaft, Cummins M11 crankshaft, Cummins 6CT crankshaft, CAT3306 Crankshaft, CAT3066 Crankshaft, diesel engine, diesel engine parts, diesel generator crankshaft, engine crankshaft, diesel engine crankshaft, crankshaft, marine crankshaft, marine diesel, Marine engine parts, crank, cranks, China marine diesel engine crankshaft manufacturer, China marine crankshaft manufacturer, forged steel crankshaft, Rebuilt diesel engines, cummins crankshaft, cummins crank, caterpillar crankshaft, cummins engine parts">
<% end %>

<%= content_for :header do %>
  How to Find Us
<% end %>

<%= content_for :js do %>
  <script> App.loadContent('#contacts .info', "http://www.heyook.com/dieselcrankshafts.com/contacts.html"); </script>
<% end %>

<div id="contacts" class="overview">
  <div class="info">
  </div>
  <br />
  <dl>
    <dt>Submit your inquery here!</dt>
    <dd>
      <div id="inquery-form">
        <%= form_tag('/inquery') do -%>
          <%= label_tag 'name'%><br />
          <%= text_field_tag 'name'%> <br />
          <%= label_tag 'email'%><br />
          <%= text_field_tag 'email'%><br />
          <%= label_tag 'company name'%><br />
          <%= text_field_tag 'company'%><br />
          <%= label_tag 'subject'%><br />
          <%= text_field_tag 'subject'%> <br />
          <%= label_tag 'content'%><br />
          <%= text_area_tag 'body'%><br />
          <%= submit_tag 'Submit' %><br />
        <% end -%>
      </div>
    </dd>
  </dl>
  
</div>

app/views/home/equipments.html.erb
<%= content_for :slides do %>
  <div><%= image_tag('equipments/Main.jpg')%></div>
<% end %>

<%= content_for :title do %>
  Equipments
<% end %>

<%= content_for :meta_info do %>
  <meta name="description" content=" Liaoning 518 Internal Combustion Engine Fittings Company provides high quality crankshafts for diesel engines, Cummins Crankshafts, Cummins K50, Cummins K38, Cummins K19, Caterpillar crankshafts, Perkins Crankshafts, DEUTZ crankshafts, Steyr Crankshafts, ISUZU Crankshafts and much more.">
  <meta name="keywords" content=" Cummins K50 crankshaft, Cummins K38 crankshaft, Cummins K19 crankshaft, Cummins NT855 crankshaft, Cummins M11 crankshaft, Cummins 6CT crankshaft, CAT3306 Crankshaft, CAT3066 Crankshaft, diesel engine, diesel engine parts, diesel generator crankshaft, engine crankshaft, diesel engine crankshaft, crankshaft, marine crankshaft, marine diesel, Marine engine parts, crank, cranks, China marine diesel engine crankshaft manufacturer, China marine crankshaft manufacturer, forged steel crankshaft, Rebuilt diesel engines, cummins crankshaft, cummins crank, caterpillar crankshaft, cummins engine parts">
<% end %>

<%= content_for :header do %>
  Equipments
<% end %>

<div id="equipments" class="overview">
  <ul class="equipments">
    <li><%= image_tag('equipments/G_5000t.jpg')%><br/><div>Germany 5000T Press Production Line</div></li> 
    <li><%= image_tag('equipments/G_Hammer.jpg')%><br/><div>Germany Electric & Hydraulic Counter Blow Hammer Production Line</div></li>
    <li><%= image_tag('equipments/J_Grinder.jpg')%><br/><div>Japan TOYODA NC Grinder</div></li>
    <li><%= image_tag('equipments/G_VDF.jpg')%><br/><div>Germany VDF-400 NC Lathe</div></li>
    <li><%= image_tag('equipments/G_AEG.jpg')%><br/><div>Germany AEG Quenching Machine</div></li>
    <li><%= image_tag('equipments/IPSEN.jpg')%><br/><div>IPSEN Nitriding Furnace</div></li>
    <li><%= image_tag('equipments/G_Meter.jpg')%><br/><div>Germany Profile Meter</div></li>
    <li><%= image_tag('equipments/G_measure.jpg')%><br/><div>Germany 3-Dimensional Measuring Machine</div></li>
  </ul>
</div>

app/views/home/index.html.erb
<%= content_for :slides do %>
  <div><%= image_tag('tractor2.jpg')%></div>
  <div><%= image_tag('tracktor.jpg')%></div>
  <div><%= image_tag('ship.jpg')%></div>
  <div><%= image_tag('engine.jpg')%></div>
<% end %>

<%= content_for :meta_info do %>
  <meta name="description" content=" Liaoning 518 Internal Combustion Engine Fittings Company provides high quality crankshafts for diesel engines, Cummins Crankshafts, Caterpillar crankshafts, Perkins Crankshafts, DEUTZ crankshafts, Steyr Crankshafts, ISUZU Crankshafts and much more.">
  <meta name="keywords" content=" tractor, part, parts, engine, engine parts, diesel engine, diesel engine parts, diesel generator crankshaft, engine crankshaft, diesel engine crankshaft, crankshaft, marine crankshaft, marine diesel, Marine engine parts, crank, cranks, China marine diesel engine crankshaft manufacturer, China marine crankshaft manufacturer, forged steel crankshaft, Rebuilt diesel engines, cummins crankshaft,  cummins crank, caterpillar crankshaft, cummins engine parts">
<% end %>

<%= content_for :title do %>
  Home Page
<% end %>

<%= content_for :header do %>
  Home Page
<% end %>

<%= content_for :js do %>
  <script> App.loadContent('#main_div', "http://heyook.com/dieselcrankshafts.com/main.html"); </script>
<% end %>

<div id="main_div" class="overview">
  
</div>

app/views/home/load.html.erb
<%= @body %>

app/views/home/load.js.erb
$('#main_div').html("<%= escape_javascript( @body )%>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us">
<head>
   <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   <%= yield :meta_info %>
   <title><%= yield :title %></title>
   <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
   <link href="/stylesheets/print.css" media="print" rel="stylesheet" type="text/css" />
   <!--[if IE]>
       <link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
   <![endif]-->
   <link href="/facebox/facebox.css" media="screen" rel="stylesheet" type="text/css" />
   <script src="/javascripts/jquery-1.4.4.js" type="text/javascript"></script> 
   <script src="/javascripts/jquery-ui-1.8.10.custom.min.js" type="text/javascript"></script> 
   <script src="/javascripts/jquery.tinyscroll.js" type="text/javascript"></script>
   <script src="/javascripts/jquery.easing.1.3.js" type="text/javascript"></script>
   <script src="/javascripts/slides.min.jquery.js" type="text/javascript"></script>
   <script src="/facebox/facebox.js" type="text/javascript"></script>
   <script src="/javascripts/application.js" type="text/javascript"></script> 
   
   <%= yield :js %>
   
   <%= csrf_meta_tag %>
</head>
<body>
  <%- unless flash.empty? %>
  <div id="flash">
    <%- flash.each do |name, msg| %>
      <div class="<%= name%>">
        <%= msg %>
      </div>
    <%- end %>
  </div>  
  <%- end %>
  <div class='two-col' id='container'>
    <div id='sidebar'>
      <div id="navbar">
        <ul class='nice-links'>
          <%= nice_link 'main', 'Main', root_path %>
          <%= nice_link 'products', 'Products', products_path %>
          <%= nice_link 'equipments', 'Equipments', equipments_path %>
          <%= nice_link 'about', 'About Us', about_path %>
          <%= nice_link 'contacts', 'Contacts', contacts_path %>
        </ul>
      </div>
      <div class="sidefill">
        <h3 class="news">News Update</h3>
        <div id="news_updates"></div>
      </div>
    </div>
    <div id='content'>
      <div id="top-logo">
        <h2>Diesel Crankshaft Company</h2>
        <h4 class="slogan">Brave to lead, Pursue to Excellence <a href="/contacts">Call us Today! </a></h4>
      </div>
      <div id='main-content'>
        <div id="slides">
          <div class="slides_container">
            <%= yield :slides %>
          </div>
        </div>
        <h2 class='header'><%= yield :header %></h2>
        <div class='scrolldiv'>
          <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
        	<div class="viewport">
            <%= yield %> 
          </div>
        </div>
      </div>
      <div class="rside-fill">
        <h3 class="side-header">Achievements</h3>
        <ul>
          <li><div class="image-wrapper"><a rel="facebox" href="/images/certs/ISO9001.jpg"><img src="/images/certs/ISO9001_s.png"></a></div></li>
          <li><div class="image-wrapper"><a rel="facebox" href="/images/certs/TS16949.jpg"><img src="/images/certs/TS16949_s.png"></a></div></li>
        </ul>
      </div>
    </div>  
    <div id='footer'>
      <ul>
        <li><a href="/">Main</a></li>
        <li><a href="products.html">Products</a></li>
        <li><a href="equipments.html">Equipments</a></li>
        <li><a href="about.html">About Us</a></li>
        <li><a href="contacts.html">Contacts</a></li>
      </ul>
    </div>  
    <div id="copyright">Diesel Crankshafts Company &copy; 2011</div>
    <div id="keyword-hide">tractor, part, parts, engine, engine parts, diesel engine, diesel engine parts, diesel generator crankshaft, engine crankshaft, diesel engine crankshaft, crankshaft, marine crankshaft, marine diesel, Marine engine parts, crank, cranks, China marine diesel engine crankshaft manufacturer, China marine crankshaft manufacturer, forged steel crankshaft, Rebuilt diesel engines, cummins crankshaft,  cummins crank, caterpillar crankshaft, cummins engine parts</div>
  </div>
  <div>
    <%= render 'home/google'%>
  </div>
</body>
</html>

app/views/layouts/product.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us">
<head>
   <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   <meta name="description" content=" Liaoning 518 Internal Combustion Engine Fittings Company provides high quality crankshafts for diesel engines, Cummins Crankshafts, Cummins K50, Cummins K38, Cummins K19, Caterpillar crankshafts, Perkins Crankshafts, DEUTZ crankshafts, Steyr Crankshafts, ISUZU Crankshafts and much more.">
   <meta name="keywords" content=" Cummins K50 crankshaft, Cummins K38 crankshaft, Cummins K19 crankshaft, Cummins NT855 crankshaft, Cummins M11 crankshaft, Cummins 6CT crankshaft, CAT3306 Crankshaft, CAT3066 Crankshaft, diesel engine, diesel engine parts, diesel generator crankshaft, engine crankshaft, diesel engine crankshaft, crankshaft, marine crankshaft, marine diesel, Marine engine parts, crank, cranks, China marine diesel engine crankshaft manufacturer, China marine crankshaft manufacturer, forged steel crankshaft, Rebuilt diesel engines, cummins crankshaft, cummins crank, caterpillar crankshaft, cummins engine parts">
   <title><%= yield :title %></title>
   <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
   <link href="/stylesheets/print.css" media="print" rel="stylesheet" type="text/css" />
   <!--[if IE]>
       <link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
   <![endif]-->
   <link href="/facebox/facebox.css" media="screen" rel="stylesheet" type="text/css" />
   <script src="/javascripts/jquery-1.4.4.js" type="text/javascript"></script> 
   <script src="/javascripts/jquery-ui-1.8.10.custom.min.js" type="text/javascript"></script> 
   <script src="/javascripts/jquery.tinyscroll.js" type="text/javascript"></script>
   <script src="/javascripts/jquery.easing.1.3.js" type="text/javascript"></script>
   <script src="/javascripts/slides.min.jquery.js" type="text/javascript"></script>
   <script src="/facebox/facebox.js" type="text/javascript"></script>
   <script src="/javascripts/application.js" type="text/javascript"></script> 
   <%= csrf_meta_tag %>
  
   <script> App.loadContent('#product_div .text', "http://heyook.com/dieselcrankshafts.com/products.html"); </script>
   <%= yield :js %>
   
</head>
<body>
  <%- unless flash.empty? %>
  <div id="flash">
    <%- flash.each do |name, msg| %>
      <div class="<%= name%>">
        <%= msg %>
      </div>
    <%- end %>
  </div>  
  <%- end %>
  <div class='two-col container_products' id='container'>
    <div id='sidebar'>
      <div id="navbar">
        <ul class='nice-links'>
          <%= nice_link 'main', 'Main', root_path %>
          <%= nice_link 'products', 'Products', products_path %>
          <%= nice_link 'equipments', 'Equipments', equipments_path %>
          <%= nice_link 'about', 'About Us', about_path %>
          <%= nice_link 'contacts', 'Contacts', contacts_path %>
        </ul>
      </div>
      <div class="sidefill">
        <h3 class="news">News Update</h3>
        <div id="news_updates"></div>
      </div>
    </div>
    <div id='content'>
      <div id="top-logo">
        <h2>Diesel Crankshaft Company</h2>
        <h4 class="slogan">Brave to lead, Pursue to Excellence <a href="/contacts">Call us Today! </a></h4>
      </div>
      <div id='main-content', class="products">
        <div id="slides", class="products">
          <div class="slides_container">
            <%= yield :slides %>
          </div>
        </div>
        <h2 class='header'><%= yield :header %></h2>
        <div class='scrolldiv'>
          <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
        	<div class="viewport">
            <%= yield %> 
          </div>
        </div>
      </div>
    </div>  
    <div id='footer'>
      <ul>
        <li><a href="/">Main</a></li>
        <li><a href="products.html">Products</a></li>
        <li><a href="equipments.html">Equipments</a></li>
        <li><a href="about.html">About Us</a></li>
        <li><a href="contacts.html">Contacts</a></li>
      </ul>
    </div>  
    <div id="copyright">Diesel Crankshafts Company &copy; 2011</div>
    <div id="keyword-hide">tractor, part, parts, engine, engine parts, diesel engine, diesel engine parts, diesel generator crankshaft, engine crankshaft, diesel engine crankshaft, crankshaft, marine crankshaft, marine diesel, Marine engine parts, crank, cranks, China marine diesel engine crankshaft manufacturer, China marine crankshaft manufacturer, forged steel crankshaft, Rebuilt diesel engines, cummins crankshaft,  cummins crank, caterpillar crankshaft, cummins engine parts</div>
  </div>
  <div>
    <%= render 'home/google'%>
  </div>
</body>
</html>

app/views/products/_product.html.erb
<%= prod_box product do %>
  <h4 class="product_name"><%= product.name %></h4>
  <%= link_to image_tag(product.pictures.first.image.url(:thumb)), product.pictures.first.image.url, :class => "product", :rel => "facebox" %>
<% end %>

app/views/products/index.html.erb
<%= content_for :slides do %>
  <div><%= image_tag('products/CumminsM11.png')%></div>
  <div><%= image_tag('products/CUMMINSNT855.png')%></div>
  <div><%= image_tag('products/k38.png')%></div>
  <div><%= image_tag('products/k50.png')%></div>
<% end %>

<%= content_for :title do %>
  Diesel Crank Shafts Products
<% end %>

<%= content_for :header do %>
  Products
<% end %>

<div id="product_div" class="overview">
  <div class="text"></div>
  <br/>
  <div class="images products" id="products_list">
    <%= render products %>
  </div>
  <div class="clear"></div>
</div>